version: '3'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        environment:
            - MONGO_URL=mongodb://mongo:27017/social-platform

    mongo:
        image: mongo:4.4
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
